VAGRANTFILE_API_VERSION = "2"

$conda_installation = <<SCRIPT
yum -y install bzip2
curl https://repo.continuum.io/miniconda/Miniconda2-4.3.14-Linux-x86_64.sh -o miniconda.sh || exit 1;
bash miniconda.sh -b || exit 1;

grep -q miniconda ~/.bashrc;
if [[ ${?} -ne 0 ]]; then
    echo "export PATH=\"${HOME}/miniconda2/bin:\${PATH}\"" >> ~/.bashrc
fi

source ~/.bashrc

conda info || exit 1;
rm miniconda.sh || exit 1;
SCRIPT

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "centos/7"

  config.vm.provision "shell", inline: $conda_installation
end

